services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883/tcp"  # MQTT port
      - "9001:9001"  # WebSocket port (optional)
    volumes:
      - c:/iot_class/mosquitto_data:/mosquitto/data
      - c:/iot_class/mosquitto_log:/mosquitto/log
      - ./config/mosquitto:/mosquitto/config
      - ./config/mosquitto/passwd:/mosquitto/config/passwd
